name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create application.properties for test
        run: |
#          mkdir -p src/test/resources
#          echo "spring.datasource.url=jdbc:h2:mem:testdb" > src/test/resources/application.properties
#          echo "spring.datasource.driver-class-name=org.h2.Driver" >> src/test/resources/application.properties
#          echo "spring.datasource.username=sa" >> src/test/resources/application.properties
#          echo "spring.datasource.password=" >> src/test/resources/application.properties
#          echo "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect" >> src/test/resources/application.properties
#          echo "spring.jpa.hibernate.ddl-auto=create" >> src/test/resources/application.properties
#          echo "spring.jwt.secret=tmpSecretForTest" >> src/test/resources/application.properties
#          echo "spring.data.web.pageable.default-page-size=30" >> src/test/resources/application.properties
#          echo "spring.data.web.pageable.max-page-size=1000" >> src/test/resources/application.properties
          touch ./src/test/resources/application.properties
          echo "${{ secrets.TEST_APPLICATION_PROPERTIES }}" > ./src/test/resources/application.properties
          cat ./src/test/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Check if tests passed
        id: check_tests
        run: echo "Tests Passed" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: env.check_tests == 'Tests Passed'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        if: env.check_tests == 'Tests Passed'
        run: docker build . -t carrotbat410/spring-lol-repository

      - name: Push Docker image
        if: env.check_tests == 'Tests Passed'
        run: docker push carrotbat410/spring-lol-repository

      - name: Deploy to Server
        if: env.check_tests == 'Tests Passed'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull carrotbat410/spring-lol-repository
            docker-compose down
            docker-compose up -d